language: node_js
branches:
  only:
    - master
    - stable
node_js:
  - 0.8
  - 0.10
notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.net##turbonode"
    on_success: always
    on_failure: always
